name: Publish to GitHub Package Repository

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - aktivitetslogg/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: "write" # For å submitte dependency graph
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Java and build
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/wrapper-validation-action@v3.5.0
      - uses: gradle/actions/setup-gradle@v4
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - run: ./gradlew --no-configuration-cache test
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y%m%d).$(echo $GITHUB_RUN_NUMBER).$(echo $GITHUB_SHA | cut -c 1-6)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # ratchet:ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: true
    outputs:
      tag: ${{ env.RELEASE_TAG }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21.x
          cache: 'gradle'
      - name: publish
        run: ./gradlew -Pversion="$(echo ${{ needs.release.outputs.tag }})" publish
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
