name: Publish to GitHub Package Repository

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - aktivitetslogg/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java and build
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1.1.0
      - uses: gradle/gradle-build-action@v2.6.1
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          arguments: --configuration-cache test
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y%m%d%H%M%s).$(echo $GITHUB_SHA | cut -c 1-12)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # ratchet:ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: true
    outputs:
      tag: ${{ env.RELEASE_TAG }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.x
          cache: 'gradle'
      - name: publish
        run: ./gradlew -Pversion="$(echo ${{ needs.release.outputs.tag }})" publish
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
